# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b34647b1e60431dc95d8931583e3026ceb7898a6790033440579046e4186651c5bfbeb4197cc6fd956225e29328c931e910fbdb0a4777af3210476718af4329

test:
  secret_key_base: 7d3d2ba197be94f81db9be5f053740b7d64a04a012d57980606a5caefe04f19455ed35fccf11e3316387ce913960fca1b724d318049f3209d71793413a4557e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
